import About from '@/components/About';
import MainContainer from '@/components/MainContainer';
import NavBar from '@/components/NavBar'
import OurServices from '@/components/OurServices';
import OurTeam from '@/components/OurTeam';
import Testimonials from '@/components/Testimonials';
import Head from 'next/head'
import { request } from "../lib/datocms";

const HOMEPAGE_QUERY = `{
  allSobres {
    id
    titulo
    foto {
      id
      url
    }
    _status
    _firstPublishedAt
  }

  _allSobresMeta {
    count
  }
}`;
export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY
  });
  return {
    props: { data },
    revalidate: 5
  };
}

export default function Home(props:any) {
  const {data} = props;
  console.log(data.allSobres[0])

  return (
    <>
      <Head>
        <title>Dra. Giselli Alves</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <MainContainer/>
      <About/>
      <Testimonials props={data}/>
      <OurServices/>
      <OurTeam/>
    </>
  )
}
